# Team Choice for Weekly FPL Challenge

In [1]:
import pandas as pd

## GW18 Challenge - Out of the Box

In [9]:
df = pd.read_csv('../data/predictedpoints.csv')

points_col = '18_pts_no_prob'
prob_col = '18_prob'

df = df.sort_values(by=points_col, ascending=False) ##Sort players based on the adjusted points
df = df[df[prob_col] >= 0.8] ##Filter out players with less than 85% probability of playing

df.head()

,ID,Name,Team,Pos,Price,18_pts_no_prob,18_prob,18_with_prob,19_pts_no_prob,19_prob,...,22_with_prob,23_pts_no_prob,23_prob,23_with_prob,24_pts_no_prob,24_prob,24_with_prob,25_pts_no_prob,25_prob,25_with_prob
327,328,M.Salah,LIV,MID,13.5,7.21799,0.94109,6.79279,6.28734,0.94109,...,6.34568,6.90210,0.94109,6.49551,5.91986,0.94109,5.57113,7.05433,0.94109,6.63878
181,182,Palmer,CHE,MID,11.3,5.95017,0.94069,5.59725,5.59567,0.94069,...,6.14421,4.45808,0.94069,4.19366,6.67830,0.94069,6.28219,5.03684,0.94069,4.73810
350,351,Haaland,MCI,FWD,14.8,5.57870,0.94090,5.24900,4.71527,0.94090,...,4.11599,4.67162,0.94090,4.39552,3.46275,0.94090,3.25810,5.09259,0.94090,4.79161
400,401,Isak,NEW,FWD,9.0,4.96032,0.94076,4.66649,4.26842,0.94076,...,4.93712,5.04325,0.94076,4.74450,5.07848,0.94076,4.77764,3.83687,0.94076,3.60958
567,568,Muric,IPS,GK,4.4,4.95153,0.94937,4.70086,3.73674,0.94937,...,3.77351,5.33172,0.94937,5.06180,3.10978,0.94937,2.95234,4.76360,0.94937,4.52243

In [10]:
## No budget so we choose the players with the most points based on our formation choice
### In the script below, we determine which formation to go for to maximise our points return
formations = [[3,2,3],[3,3,2],[3,4,1],[4,2,2],[4,3,1]]
formation_positions = ['DEF', 'MID', 'FWD']
cache = dict() ## Save responses to avoid recomputations

final_result = [[],0,[]] ## [formation, total expected points, list of chosen players]
for formation in formations:
    result = [0,[]] ## Subset of the final result for each formation iteration
    for i in range(len(formation)):
        if (formation_positions[i],formation[i]) in cache.keys():
            points = cache[(formation_positions[i],formation[i])][0].sum()
            players = list(cache[(formation_positions[i],formation[i])][1])
        else:
            points = df[df.Pos == formation_positions[i]][points_col][:formation[i]].sum()
            players = list(df[df.Pos == formation_positions[i]].ID[:formation[i]])
            cache[(formation_positions[i],formation[i])] = [points,players]
        result[0] += points
        result[1] += players
    if result[0] > final_result[1]:
        final_result = [formation,result[0],result[1]]

final_result[1] += df[df.Pos == 'GK'][points_col][:1].sum()
final_result[2] += list(df[df.Pos == 'GK'].ID[:1])
print(final_result)

[[3, 3, 2], 45.26365, [311, 335, 18, 328, 182, 366, 351, 401, 568]]

In [11]:
## See the players in the optimal final team
df['chosen'] = df.ID.isin(final_result[2])
df[df['chosen']== True]

,ID,Name,Team,Pos,Price,18_pts_no_prob,18_prob,18_with_prob,19_pts_no_prob,19_prob,...,23_pts_no_prob,23_prob,23_with_prob,24_pts_no_prob,24_prob,24_with_prob,25_pts_no_prob,25_prob,25_with_prob,chosen
327,328,M.Salah,LIV,MID,13.5,7.21799,0.94109,6.79279,6.28734,0.94109,...,6.90210,0.94109,6.49551,5.91986,0.94109,5.57113,7.05433,0.94109,6.63878,True
181,182,Palmer,CHE,MID,11.3,5.95017,0.94069,5.59725,5.59567,0.94069,...,4.45808,0.94069,4.19366,6.67830,0.94069,6.28219,5.03684,0.94069,4.73810,True
350,351,Haaland,MCI,FWD,14.8,5.57870,0.94090,5.24900,4.71527,0.94090,...,4.67162,0.94090,4.39552,3.46275,0.94090,3.25810,5.09259,0.94090,4.79161,True
400,401,Isak,NEW,FWD,9.0,4.96032,0.94076,4.66649,4.26842,0.94076,...,5.04325,0.94076,4.74450,5.07848,0.94076,4.77764,3.83687,0.94076,3.60958,True
567,568,Muric,IPS,GK,4.4,4.95153,0.94937,4.70086,3.73674,0.94937,...,5.33172,0.94937,5.06180,3.10978,0.94937,2.95234,4.76360,0.94937,4.52243,True
310,311,Alexander-Arnold,LIV,DEF,7.1,4.70271,0.94061,4.42342,4.32583,0.94061,...,4.21417,0.94061,3.96390,3.96656,0.94061,3.73099,4.37673,0.94061,4.11681,True
365,366,B.Fernandes,MUN,MID,8.4,4.50933,0.94123,4.24429,4.48604,0.94123,...,3.67898,0.94123,3.46275,4.11642,0.94123,3.87447,4.02258,0.94123,3.78615,True
334,335,Robertson,LIV,DEF,5.9,3.89240,0.90655,3.52863,3.60697,0.90655,...,3.50987,0.90655,3.18185,3.35126,0.90655,3.03806,3.64392,0.90655,3.30338,True
17,18,Saliba,ARS,DEF,6.3,3.50050,0.92136,3.22522,3.80938,0.92136,...,3.69268,0.92136,3.40228,3.42073,0.92136,3.15172,3.71742,0.92136,3.42508,True

## GW17 Challenge â€“ Home for the holidays
Players at home earn double points. Budget is unlimited. Choose 9 players with any of the following 5 formations: `3-2-3`, `3-3-2`,`3-4-1`,`4-2-2`, and `4-3-1`. The teams at home are:  `AVL`, `BRE`, `IPS`, `WHU`, `CRY`, `EVE`, `FUL`, `LEI`, `MUN`, and `TOT`.

### Adjust points based on GW17 Rules

In [75]:
home_teams = ['AVL', 'BRE', 'IPS', 'WHU', 'CRY', 'EVE', 'FUL', 'LEI', 'MUN', 'TOT']
points_col = '17_pts_no_prob'
prob_col = '17_prob'

df = pd.read_csv('../data/predictedpoints.csv')
df['multiplier'] = 1 + df['Team'].isin(home_teams).astype('int') ##Create a 2X multiplier if team is playing at home
df[points_col] = df['multiplier'] * df[points_col] ##Adjust points based on the multiplier

df = df.sort_values(by=points_col, ascending=False) ##Sort players based on the adjusted points
df = df[df[prob_col] >= 0.85] ##Filter out players with less than 85% probability of playing

df.head(20)

,ID,Name,Team,Pos,Price,17_pts_no_prob,17_prob,17_with_prob,18_pts_no_prob,18_prob,...,22_pts_no_prob,22_prob,22_with_prob,23_pts_no_prob,23_prob,23_with_prob,24_pts_no_prob,24_prob,24_with_prob,multiplier
365,366,B.Fernandes,MUN,MID,8.4,9.88484,0.94121,4.65187,4.95893,0.94121,...,5.32636,0.94121,5.01324,4.86993,0.94121,4.58364,5.23666,0.94121,4.92881,2
502,503,Son,TOT,MID,9.8,8.97804,0.94199,4.22860,3.92844,0.94199,...,3.58481,0.94199,3.37685,5.79242,0.94199,5.45639,4.15604,0.94199,3.91494,2
46,47,Martinez,AVL,GK,5.0,7.81236,0.94938,3.70843,4.61405,0.94938,...,4.83068,0.94938,4.58613,3.38601,0.94938,3.21460,4.07342,0.94938,3.86721,2
567,568,Muric,IPS,GK,4.4,7.76852,0.94936,3.68757,4.93866,0.94936,...,4.00770,0.94936,3.80477,5.31914,0.94936,5.04980,3.16573,0.94936,3.00543,2
98,99,Mbeumo,BRE,MID,7.6,7.67106,0.94123,3.61012,3.18675,0.94123,...,3.35792,0.94123,3.16058,3.10592,0.94123,2.92338,3.54694,0.94123,3.33849,2
234,235,Pickford,EVE,GK,4.9,7.59434,0.94941,3.60508,4.46976,0.94941,...,3.87508,0.94941,3.67905,4.00588,0.94941,3.80323,3.57514,0.94941,3.39428,2
487,488,Forster,TOT,GK,4.3,7.52548,0.94000,3.53697,3.88584,0.94000,...,4.05775,0.94000,3.81429,3.42639,0.94000,3.22081,4.38398,0.94000,4.12094,2
513,514,Bowen,WHU,MID,7.4,7.31868,0.93719,3.42948,4.22595,0.93719,...,3.57968,0.93719,3.35483,3.34284,0.93719,3.13287,3.23684,0.93719,3.03353,2
90,91,Flekken,BRE,GK,4.5,7.14338,0.94941,3.39101,4.54848,0.94941,...,3.96819,0.94941,3.76744,4.33595,0.94941,4.11660,3.95016,0.94941,3.75033,2
382,383,Onana,MUN,GK,5.2,7.08888,0.94941,3.36514,4.04458,0.94941,...,3.54480,0.94941,3.36548,4.37539,0.94941,4.15405,3.45888,0.94941,3.28391,2
247,248,Leno,FUL,GK,5.0,6.97868,0.94941,3.31283,4.69116,0.94941,...,3.99023,0.94941,3.78837,3.87746,0.94941,3.68131,4.65454,0.94941,4.41907,2
200,201,Henderson,CRY,GK,4.4,6.69954,0.94941,3.18029,4.37112,0.94941,...,4.09802,0.94941,3.89068,3.19281,0.94941,3.03127,4.45097,0.94941,4.22578,2
246,247,Iwobi,FUL,MID,5.7,6.64676,0.94122,3.12804,3.08176,0.94122,...,3.42096,0.94122,3.21988,3.09772,0.94122,2.91564,3.09607,0.94122,2.91409,2
109,110,Wissa,BRE,FWD,6.2,6.55084,0.93707,3.06931,2.64379,0.93707,...,2.79795,0.93707,2.62189,2.70392,0.93707,2.53378,2.98818,0.93707,2.80015,2
254,255,Robinson,FUL,DEF,4.8,6.46704,0.94123,3.04350,3.40584,0.94123,...,3.36095,0.94123,3.16343,3.19159,0.94123,3.00403,3.43580,0.94123,3.23389,2
494,495,Pedro Porro,TOT,DEF,5.6,6.44892,0.94123,3.03495,3.29699,0.94123,...,3.22980,0.94123,3.03997,3.54898,0.94123,3.34039,3.72323,0.94123,3.50439,2
57,58,Watkins,AVL,FWD,8.9,6.38250,0.94122,3.00365,2.70876,0.94122,...,2.35579,0.94122,2.21730,3.49471,0.94122,3.28928,2.99485,0.94122,2.81880,2
81,82,Solanke,TOT,FWD,7.5,6.37660,0.87278,2.78269,3.07897,0.87278,...,3.12363,0.87278,2.72624,3.82391,0.87278,3.33744,3.07404,0.87278,2.68296,2
524,525,Kudus,WHU,MID,6.2,6.33314,0.85623,2.71132,3.35136,0.85623,...,3.21680,0.85623,2.75433,2.79647,0.85623,2.39443,2.72715,0.85623,2.33507,2
43,44,Konsa,AVL,DEF,4.4,6.20560,0.91498,2.83899,3.22305,0.91498,...,3.19768,0.91498,2.92580,3.17323,0.91498,2.90343,3.05309,0.91498,2.79351,2

In [76]:
## No budget so we choose the players with the most points based on our formation choice
### In the script below, we determine which formation to go for to maximise our points return
formations = [[3,2,3],[3,3,2],[3,4,1],[4,2,2],[4,3,1]]
formation_positions = ['DEF', 'MID', 'FWD']
cache = dict() ## Save responses to avoid recomputations

final_result = [[],0,[]] ## [formation, total expected points, list of chosen players]
for formation in formations:
    result = [0,[]] ## Subset of the final result for each formation iteration
    for i in range(len(formation)):
        if (formation_positions[i],formation[i]) in cache.keys():
            points = cache[(formation_positions[i],formation[i])][0].sum()
            players = list(cache[(formation_positions[i],formation[i])][1])
        else:
            points = df[df.Pos == formation_positions[i]][points_col][:formation[i]].sum()
            players = list(df[df.Pos == formation_positions[i]].ID[:formation[i]])
            cache[(formation_positions[i],formation[i])] = [points,players]
        result[0] += points
        result[1] += players
    if result[0] > final_result[1]:
        final_result = [formation,result[0],result[1]]

final_result[1] += df[df.Pos == 'GK'][points_col][:1].sum()
final_result[2] += list(df[df.Pos == 'GK'].ID[:1])
print(final_result)

[[3, 4, 1], 67.33738000000001, [255, 495, 44, 366, 503, 99, 514, 110, 47]]

In [ ]:
## See the players in the optimal final team
df['chosen'] = df.ID.isin(final_result[2])
df[df['chosen']== True]

,ID,Name,Team,Pos,Price,17_pts_no_prob,17_prob,17_with_prob,18_pts_no_prob,18_prob,...,22_prob,22_with_prob,23_pts_no_prob,23_prob,23_with_prob,24_pts_no_prob,24_prob,24_with_prob,multiplier,chosen
365,366,B.Fernandes,MUN,MID,8.4,9.88484,0.94121,4.65187,4.95893,0.94121,...,0.94121,5.01324,4.86993,0.94121,4.58364,5.23666,0.94121,4.92881,2,True
502,503,Son,TOT,MID,9.8,8.97804,0.94199,4.22860,3.92844,0.94199,...,0.94199,3.37685,5.79242,0.94199,5.45639,4.15604,0.94199,3.91494,2,True
46,47,Martinez,AVL,GK,5.0,7.81236,0.94938,3.70843,4.61405,0.94938,...,0.94938,4.58613,3.38601,0.94938,3.21460,4.07342,0.94938,3.86721,2,True
98,99,Mbeumo,BRE,MID,7.6,7.67106,0.94123,3.61012,3.18675,0.94123,...,0.94123,3.16058,3.10592,0.94123,2.92338,3.54694,0.94123,3.33849,2,True
513,514,Bowen,WHU,MID,7.4,7.31868,0.93719,3.42948,4.22595,0.93719,...,0.93719,3.35483,3.34284,0.93719,3.13287,3.23684,0.93719,3.03353,2,True
109,110,Wissa,BRE,FWD,6.2,6.55084,0.93707,3.06931,2.64379,0.93707,...,0.93707,2.62189,2.70392,0.93707,2.53378,2.98818,0.93707,2.80015,2,True
254,255,Robinson,FUL,DEF,4.8,6.46704,0.94123,3.04350,3.40584,0.94123,...,0.94123,3.16343,3.19159,0.94123,3.00403,3.43580,0.94123,3.23389,2,True
494,495,Pedro Porro,TOT,DEF,5.6,6.44892,0.94123,3.03495,3.29699,0.94123,...,0.94123,3.03997,3.54898,0.94123,3.34039,3.72323,0.94123,3.50439,2,True
43,44,Konsa,AVL,DEF,4.4,6.20560,0.91498,2.83899,3.22305,0.91498,...,0.91498,2.92580,3.17323,0.91498,2.90343,3.05309,0.91498,2.79351,2,True